import { readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';
import { storeUrl } from '../web/downloads/store.js';

export function configureStoreSite(root, productId, liveValue) {
  if (!['', 'true', 'false'].includes(liveValue)) {
    throw new Error('STORE_LISTING_LIVE must be true, false or unset.');
  }
  const config = { productId, live: liveValue === 'true' };
  const url = storeUrl(config);
  const path = join(root, 'index.html');
  const html = readFileSync(path, 'utf8');
  const anchor = /id="store-win-x64"(?: href="[^"]*")?(?: hidden)?/g;
  if ([...html.matchAll(anchor)].length !== 1) throw new Error('Expected one Store anchor in index.html.');
  const result = html.replace(anchor, `id="store-win-x64"${url ? ` href="${url}"` : ' hidden'}`)
    .replace(/id="store-description"(?: hidden)?/, `id="store-description"${url ? '' : ' hidden'}`);
  writeFileSync(path, result);
  writeFileSync(join(root, 'store-config.js'),
    '// Generated by tool/configure_store_site.mjs; only public listing configuration.\n'
    + `export const STORE_CONFIG = ${JSON.stringify(config)};\n`);
}

if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
  const product = JSON.parse(readFileSync(new URL('../packaging/windows/store-product.json', import.meta.url)));
  configureStoreSite(
    fileURLToPath(new URL('../web/downloads/', import.meta.url)),
    product.productId,
    process.env.STORE_LISTING_LIVE || '',
  );
  console.log(`Store website link ${process.env.STORE_LISTING_LIVE === 'true' ? 'enabled' : 'disabled'}.`);
}
