name: build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
      - name: Restore
        run: dotnet restore src/MovieDb.App/MovieDb.App.csproj
      - name: Build
        run: dotnet build src/MovieDb.App/MovieDb.App.csproj -c Release --no-restore
